### ISSUE TITLE
isprime(1) returns true

### ISSUE THREAD

**Issue by ssmccoy** [e36freak/awk-libs#2]
Unfortunately `1` is not a prime number, the definition of primes is that it's only _proper factor_ is `1`, or otherwise stated:

"A natural number (i.e. 1, 2, 3, 4, 5, 6, etc.) is called a prime number (or a prime) if it has exactly two positive divisors, 1 and the number itself." If this was not true, then all prime number sieves would not work. Unfortunately, if 1 was a prime number, then Euclid's fundamental theorem of arithmetic would not hold, which states "every integer greater than 1 either is prime itself or is the product of prime numbers". Various prime number sieve methods would not work either.

**Comment by rdebath** [comment]
False would be more wrong because `1` is NOT a composite number.
Perhaps it should return `Out of Cheese ERROR`

In reality, one acts just like a prime, but it's a pain to keep saying "all primes except one" when you want to prove things later. So the definition was changed to exclude `1` and put it into a special class all by itself.

Though, I suspect it's more accurate to call it a 'Domain error' and (for the library) simply state in the documentation that:

```
## usage: isprime(number)
## returns 1 if "number" is a prime number, otherwise 0. "number" must be a
## positive integer greater than one
```

**Comment by ssmccoy** [comment]
Though, function is called `isprime` not `iscomposite`. :-)

**Comment by e36freak** [comment]
Documentation updated as rdebath suggested, thanks for the pedantry and sorry I've been absent for so long :)

**Comment by ssmccoy** [comment]
Welcome back!
